image: nixos/latest
sources:
  - https://git.sr.ht/~cyplo/netlify-deployer

secrets:
  - 6c23a8c1-7a30-4a7e-b3b7-0171e898a7d3
  - 6b127d6f-e950-462e-a383-3cb6ae0ea60d
tasks:
  - github_push: |
      set +xv
      cd netlify-deployer
      GITHUB_TOKEN=`cat ~/.github_token`
      git remote add github https://cyplo:$GITHUB_TOKEN@github.com/cyplo/netlify_deployer.git
      git push github master --tags --force

  - pypi_publish: |
      set +xv
      cd netlify-deployer
      nix-shell --pure --run 'python setup.py sdist bdist_wheel'
      if [ $(git tag --points-at HEAD | wc -m) -ne 0 ]; then  nix-shell -p python38Packages.twine --run 'twine upload dist/*'; fi
